language: rust
rust:
  - stable
#  - 1.31.0
#  - 1.22.0
before_script:
  - rustup component add rustfmt
script:
  - cargo fmt -- --check --verbose
  - cargo test --verbose --all
  - cargo build --verbose --all
  - cargo build --verbose --no-default-features --features=minimal
  - cargo build --verbose --no-default-features --features=key-value-db
  - cargo build --verbose --no-default-features --features=electrum

notifications:
  email: false

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
cache: cargo
